services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8082:8080"
      - "8443:8443"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_IMPORT: /opt/keycloak/data/import/keycloak-realm-timesheet.json
    depends_on:
      - postgres
    volumes:
      - ./keycloak/keycloak-realm-timesheet.json:/opt/keycloak/data/import/keycloak-realm-timesheet.json
    #  - ./keycloak/export:/tmp
    command: "start-dev --import-realm"
    #command: export --dir /tmp --realm timesheet

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak  